.github/workflows/buildAndTestStructured.yml, CMakeLists.txt, include/structured-c/Dialects.h, include/structured/CMakeLists.txt, include/structured/Dialect/CMakeLists.txt, lib/CAPI/CMakeLists.txt, lib/CAPI/Dialects.cpp, lib/CMakeLists.txt, lib/Dialect/CMakeLists.txt, python/CMakeLists.txt, python/StructuredDialects.cpp, tools/structured-lsp-server/structured-lsp-server.cpp, tools/structured-opt/structured-opt.cpp
This commit cleans up the files with boilerplate code imported from the original location of this project, the
[IREE LLVM sandbox](https://github.com/iree-org/iree-llvm-sandbox), by removing all references to the other sub-projects that were part of that repository, most notably, `add_subdirectory` and similar directives from CMake files and `include` statements and various registration mechanisms from C++ files. This brings the project into a state where it can be built and the test suite passes in CI.
=> Remove all references to Substrait-unrelated subprojects.

CONTRIBUTING.md, README.md
This PR depends on and, therefor, includes #5.
The current file only covers the most basic aspects. I plan to add CI checks to enforce formatting etc. in the near future and will extend this file as I do.
=> docs: add a basic `CONTRIBUTING.md` file

.github/workflows/build_and_test.yml
This PR how CI installs dependencies via apt: the previous code simply ran `apt-get install` without prio `apt-get update`. This may make CI break, which happened for some PRs, if the GH runner has a version of a package in cache that just got updated such that the cached URL is invalid and the package cannot be installed. By using a proper GH action, not only is that taken care of but the package is even cached such that installing it may be a bit faster.
=> ci: fix installing apt dependencies by using action

README.md, requirements.txt, third_party/CMakeLists.txt
This commit fixes several problems with the build instructions in the README and extends them. In particular, the following changes are made:
* List global prerequisites (like git, CMake, C++ compiler, etc.)
* Fix base path and define it as a first step
* Explicitly describe what paths to add to the `activate` script, including `PATH`, and adapt following commands to that
* Mention possible problems with using `lld`
* Remove the quirk with `-DABSL_ENABLE_INSTALL=ON` -- this doesn't seem to be necessary anymore
* Remove `lit` from the Python requirements because LLVM provides it in the `PATH`
* Adapt the `lit` examples to the new repository structure
=> docs: fix and extend build instructions

include/substrait-mlir/Target/SubstraitPB/Export.h
This PR updates LLVM to the latest revision available today, Nov. 6, 2024, which is llvm/llvm-project@38fffa630e, and fixes a minor breakage occuring with the update.
=> chore: update LLVM to latest revision on Nov. 6 (38fffa630e)

include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, test/Dialect/Substrait/union-distinct.mlir
Implemented union distinct set operation in tablegen with just two input operands and a result. Custom assembly to be implemented in a subsequent PR. Added new test that checks round-trip ability of the op.
=> feat: introduce `union distinct` operation

test/CMakeLists.txt
`substrait-translate` not built when running `ninja check-substrait-mlir` so I added it to dependency list.
=> fix: add `substrait-translate` as dependency to `check-substrait-mlir`

include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, test/Dialect/Substrait/union-distinct.mlir
Please only review top commit, bottom commit in [PR #16](https://github.com/substrait-io/substrait-mlir-contrib/pull/16).
Added custom assembly with explicit return type for Union Operation and adapted the tests.
=> feat: add a custom assembly with explicit return type for `union distinct` operation

.github/workflows/yapf.yml, .yapfignore, python/CMakeLists.txt, python/substrait_mlir/_mlir_libs/_substraitDialects/__init__.pyi, python/substrait_mlir/_mlir_libs/_substraitDialects/substrait.pyi
~~This PR is currently based and, therefor, includes on #14 (in order to reuse the CI build cache from that PR).~~
This PR adds semi-generated `.pyi` files that provide typing hints for the native Python modules of this repository.
=> feat: add stubs for native Python modules for type hints

include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, lib/Dialect/Substrait/IR/Substrait.cpp, test/Dialect/Substrait/union-distinct-invalid.mlir
Added return type inference for `union distinct` operation. Added a check to make sure that left and right operand types matched, not sure if this should be done or not. 
Please only review latest commit. Other two commits in other PR's ([PR 16](https://github.com/substrait-io/substrait-mlir-contrib/pull/16), [PR 17](https://github.com/substrait-io/substrait-mlir-contrib/pull/17)).
=> feat: add return type inference for `union distinct` operation

include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td
found a documentation error in cross op. @ingomueller-net
=> fix: documentation error in `cross op`

test/Dialect/Substrait/set.mlir
fix line spacing on file splits in `set op` - they were not all the same.
=> chore: fix line spacing on file splits in `set op`

include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, test/Dialect/Substrait/set.mlir, test/Target/SubstraitPB/Export/set.mlir, test/Target/SubstraitPB/Import/set.textpb
remove comma from assembly language of `set` op to make it cleaner.  
change from:
` %2 = set union_all, %0, %1 : tuple<si32>`
to:
` %2 = set union_all %0, %1 : tuple<si32>`
the extra comma felt unnecessary. I am also doing the `join` op assembly language in the same format as the non-comma version of this `set` op assembly language so thought I would make it the same. @ingomueller-net let me know what you think and if you agree (or not :)
=> chore: remove comma from assembly language of `set` op

test/Target/SubstraitPB/Export/project.mlir
There seems to have been a mix-up: the same code used for the dialect test of the `project` operation was mistakenly included in the export test for the `project` operation. I’ve now added the correct test that accurately evaluates the export functionality of the `project` operation.
@ingomueller-net
=> chore: fix incorrect export test for `project` op

test/Dialect/Substrait/fetch.mlir, test/Dialect/Substrait/named-table-invalid.mlir, test/Dialect/Substrait/named-table.mlir, test/Dialect/Substrait/plan.mlir, test/Dialect/Substrait/project-invalid.mlir, test/Target/SubstraitPB/Export/plan.mlir, test/Target/SubstraitPB/Import/plan.textpb
Saw some spacing errors in one test file and then decided I might as well go through all the test files and fixed all the spacing issues as well as removed redundant "split input file" lines from some of the tests.
=> chore: fix all test file spacing issues and remove redundant split input file lines

include/substrait-mlir/Dialect/Substrait/IR/SubstraitDialect.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/literal.mlir, test/Dialect/Substrait/types.mlir, test/Target/SubstraitPB/Export/literal.mlir, test/Target/SubstraitPB/Export/types.mlir, test/Target/SubstraitPB/Import/literal.textpb, test/Target/SubstraitPB/Import/types.textpb
Added `string` types + `string` attribute types.
This is a stacked PR, please only review latest commit (15d2e21744b2ace928e499c5d2df8b0bc1bffcae)
@ingomueller-net
=> feat: add `string` type

include/substrait-mlir/Dialect/Substrait/IR/SubstraitEnums.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td
Moves`jointype` enums to enums.td file as discussed.
=> chore: move `jointype` enums to enums.td file

test/Target/SubstraitPB/Export/plan.mlir, test/Target/SubstraitPB/Import/plan.textpb
This PR extends the import and export tests such that both paths cover the `RootRel` and the `Rel` cases. Previously, each of them only convered one of the two.
=> test: extend `Plan` tests to cover `RootRel` and `Rel` cases properly

include/substrait-mlir/Dialect/Substrait/IR/SubstraitDialect.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/literal.mlir, test/Dialect/Substrait/types.mlir, test/Target/SubstraitPB/Export/literal.mlir, test/Target/SubstraitPB/Export/types.mlir, test/Target/SubstraitPB/Import/literal.textpb, test/Target/SubstraitPB/Import/types.textpb
Introduce both timestamp types and respective attribute types: `timestamp` and `timestamp_tz`
Note this is a stacked PR: 
`timestamp` in this commit (4b01b29b470821f585b714e33fd93066e7c155e5)
`timestamp_tz` in second commit (36761b360f73dc379b7f4f7adda7cefd281d0554)
Added tests for both timestamp types but NOT for timestamp attribute types. Waiting on https://github.com/substrait-io/substrait-mlir-contrib/pull/39 to be merged and then will add those tests to project.mlir test file (similarly to integer/float types)! @ingomueller-net
=> feat: introduce `timestamp` and `timestamp_tz` types

include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/plan-invalid.mlir, test/Dialect/Substrait/plan.mlir, test/Target/SubstraitPB/Export/plan.mlir, test/Target/SubstraitPB/Import/plan.textpb
This PR implements the `AdvanceExtension` message type as a custom attribute with two `StringAttr`s as well as an `AnyType` with a parameter for the type URL to represent the `Any` messages as typed `StringAttr`s. The PR also adds those attributes to the `PlanOp` in order to represent the `advanced_extensions` message of the `Plan` message.
We do not currently need this attribute but it is one of the few missing fields of the `Plan` message as well as many other messages we have otherwise implemented, so it allows us to get to higher coverage with relatively little effort.
=> feat: implement `AdvancedExtension` and at it to `Plan`

include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/literal.mlir, test/Dialect/Substrait/types.mlir, test/Target/SubstraitPB/Export/literal.mlir, test/Target/SubstraitPB/Export/types.mlir, test/Target/SubstraitPB/Import/literal.textpb, test/Target/SubstraitPB/Import/types.textpb
This PR introduces the `date` atomic type and its associated attribute types. The `date` type represents a calendar date within the range [1000-01-01..9999-12-31]. Internally, it is stored as an `int32` value representing the number of days since the epoch date (1970-01-01).
=> feat: introduce `date` type

lib/Target/SubstraitPB/Export.cpp
This PR addresses issue #62. 
We resolve the following  compiler warnings in our code. 
`
'isa<...>' is deprecated: Use mlir::isa<U>() instead
`
`moving a local object in a return statement prevents copy elision
`
=> chore: resolve compiler warnings

include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/literal.mlir, test/Dialect/Substrait/types.mlir, test/Target/SubstraitPB/Export/literal.mlir, test/Target/SubstraitPB/Export/types.mlir, test/Target/SubstraitPB/Import/literal.textpb, test/Target/SubstraitPB/Import/types.textpb
Implements `time` type and attribute types. Tests again added for types but not for attribute types - waiting on [this PR ](https://github.com/substrait-io/substrait-mlir-contrib/pull/39) to be merged and then will add those tests to project.mlir test file (similarly to integer, float, string, binary, date etc. types)!  
This is a stacked PR, please only review latest commit (09e06f778fef22a3f051847e54e5c06fa1bf9e76)
=> feat: introduce `time` type

lib/Dialect/Substrait/IR/Substrait.cpp
There were two places left: another usage of the deprecated MLIR `cast` and a `default` label in a switch that already covers all cases.
=> chore: fix remaining compiler warnings

include/substrait-mlir/Dialect/Substrait/IR/CMakeLists.txt, include/substrait-mlir/Dialect/Substrait/IR/SubstraitAttrs.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td
This PR moves all attribute definitions from `SubstraitTypes.td` to a new file `SubstraitAttrs.td` in order to separate the definitions of the two things better. Having them in one file was acceptable for boot strapping but the file has grow significantly lately, so I think it's time to clean up a bit.
=> chore: move attribute definitions to dedicated file

include/substrait-mlir/Dialect/Substrait/IR/CMakeLists.txt, include/substrait-mlir/Dialect/Substrait/IR/Substrait.h, include/substrait-mlir/Dialect/Substrait/IR/SubstraitAttrs.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitInterfaces.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/Export.cpp, test/Dialect/Substrait/literal.mlir, test/Target/SubstraitPB/Import/literal.textpb
This allows to omit the type of an attribute from the assembly if it can be inferred from the attribute value. For example, the type is redundant in `#substrait.timestamp<100us> : !substrait.timestamp`. The built-in `TypedAttrInterface`, however, forces the appearance of the type in the assembly. The new interface is almost identical but does not enforce it. The PR also makes the two timestamp, the date, and the time attributes implement that interface.
=> feat: elide attribute type with new `StaticallyTypedAttrInterface`

include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/plan.mlir, test/Target/SubstraitPB/Export/plan.mlir, test/Target/SubstraitPB/Import/plan.textpb
This PR adds support for the `expected_type_urls` field of the `Plan` message. This is pretty straight-forward: the repeated field of string becomes an `ArrayAttr` of `StringAttr`s. We don't really need this field currently but it's the last missing field of the `Plan` message, so it allows us to tick that message type off.
=> feat: implement `Plan.expected_type_urls` field

include/substrait-mlir/Dialect/Substrait/IR/Substrait.h, include/substrait-mlir/Dialect/Substrait/IR/SubstraitInterfaces.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, lib/Target/SubstraitPB/ProtobufUtils.h, test/Dialect/Substrait/project.mlir, test/Target/SubstraitPB/Export/project.mlir, test/Target/SubstraitPB/Import/project.textpb
This PR factors out the handling of the `shared_extension` field from the `plan` op and adds that logic to the `project` op. This mainly consisted of moving the import and export logic from the functions related to the `plan` op to dedicated functions. The PR also introduces the new `ExtensibleOpInterface` that enforces an attribute called `advanced_extension` on the op that implement it and allows to deal with all such ops transparently. Since that interface depends on an attribute, the include order of the generated code of interfaces and attributes also had to be adapted. Unfortunately, the field names in the Substrait spec also vary (singular or plural), so the PR also introduces some template magic to be able to deal with protobuf message types with both spellings. With this PR, …
=> feat: factor out `advanced_extension` logic and add it to other ops

include/substrait-mlir/Dialect/Substrait/IR/SubstraitAttrs.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitEnums.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/CMakeLists.txt, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, lib/Target/SubstraitPB/ProtobufUtils.cpp, test/Dialect/Substrait/aggregate-invalid.mlir, test/Dialect/Substrait/aggregate.mlir, test/Target/SubstraitPB/Export/aggregate-invalid.mlir, test/Target/SubstraitPB/Export/aggregate.mlir, test/Target/SubstraitPB/Import/aggregate.textpb
~~This PR depends on and, therefor, includes #68.~~
This PR adds support for the `AggregateRel` from the Substrait spec in the form of the `aggregate` op. This is arguably the most complex op implemented so far. It has an optional enum argument that requires custom parsing, several optional regions that require custom parsing, an attribute that depends on the presence and contents of the regions and requires custom parsing to omit it in the common case, and return types that depend on the two regions and the attribute. What's more, the current version of the spec is such that it is almost impossibly to interpret "grouping sets" because it relies on protobuf message equality, which is something can protobuf does not offer. The current implementation, thus, implements a best effort by using …
=> feat: add `aggregate` op and extend functions accordingly

include/substrait-mlir/Dialect/Substrait/IR/SubstraitAttrs.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, include/substrait-mlir/Target/SubstraitPB/Import.h, lib/CAPI/Dialects.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/plan-version.mlir, test/Target/SubstraitPB/Export/plan-version.mlir, test/Target/SubstraitPB/Import/plan-version.textpb, test/python/dialects/substrait/translate.py, tools/substrait-translate/substrait-translate.cpp
~~This PR depends on and, therefor, currently includes #68.~~
This PR introduces support for the `PlanVersion` message type. This is done by introduces the `VersionAttr`, which corresponds to the `Version` message type, which, in turn, is the type of the only field of `PlanVersion`.
Since `PlanVersion` is a top-level message, this PR extends the import mechanism: when reading a protobuf message, we need to know which type it is, so when we translate a protobuf message into MLIR, we need to specify which message type the input is. The PR, thus, adds a new flag to the `substrait-translate` tool, together with a corresponding top-level translation function. This also slightly changed some existing error messages and the corresponding tests.
This PR does not yet factor out the handling of the …
=> feat: implement support for the `PlanVersion` message type

requirements-unfrozen.txt, requirements.txt
That file is now created with the following commands:
```
pip install --upgrade -r requirements-unfrozen.txt
pip freeze > requirements.txt
```
This prevents automatic updates of dependencies, which may break CI or new developers.
=> ci: freeze dependencies in `requirements.txt`

include/substrait-mlir/Dialect/Substrait/IR/SubstraitEnums.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/Import.cpp
This PR makes some clean-ups to `SubstraitEnums.td`:
* Reformat (mostly) according to `clang-format`.
* Remove unnecessary `Kind` suffix in `JoinTypeKind`.
* Move `summary` property of enum `def`s to comment.
* Rephrase those comments to make them clearer.
=> style: clean up `SubstraitEnums.td`

include/substrait-mlir/Dialect/Substrait/IR/SubstraitAttrs.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/extension-table.mlir, test/Target/SubstraitPB/Export/extension-table.mlir, test/Target/SubstraitPB/Import/extension-table.textpb
This PR is based on and, therefor, contains #72.
This PR implements the `extension_table` op, the MLIR equivalent of the `ReadRel.ExtensionTable` message. Since that message uses the `google.protobuf.Any` message type, the PR also slightly extends and improves the handling of that message in the dialect. Finally, because `extension_table` is the second op corresponding to a `ReadRel` case (after `named_table`), the PR makes some effort to factor out common logic between the two, namely, how the named structs representing the schema of the op are handled. However, there is still some opportunity for factoring out further that the PR does not do, such as defining a `ReadRelInterface`.
=> feat: implement `extension_table` op

include/substrait-mlir/Dialect/Substrait/IR/Substrait.h, include/substrait-mlir/Dialect/Substrait/IR/SubstraitEnums.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, lib/Dialect/Substrait/IR/CMakeLists.txt, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/cast.mlir, test/Target/SubstraitPB/Export/cast.mlir, test/Target/SubstraitPB/Import/cast.textpb
This PR depends on and, therefor, includes #75.
This PR implements the `cast` op, which corresponds to the `Cast` expression in Substrait. This is one of the few remaining message types we need to support to get a first TPC-H query round-tripped.
=> feat: implement `cast` op for `Cast` expression

test/Dialect/Substrait/literal.mlir, test/Target/SubstraitPB/Export/literal.mlir
Removed types of date/time attributes from the literal test and Export/literal tests to align with the timestamp tests. I noticed that these attributes were still present in date/time but not in timestamp tests - was this an oversight or intentional? Let me know if they were intentionally kept and will close the PR.
=> chore: remove type of date/time attribute from test

include/substrait-mlir/Dialect/Substrait/IR/SubstraitAttrs.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/literal.mlir, test/Dialect/Substrait/types.mlir, test/Target/SubstraitPB/Export/literal.mlir, test/Target/SubstraitPB/Export/types.mlir, test/Target/SubstraitPB/Import/literal.textpb, test/Target/SubstraitPB/Import/types.textpb
This PR introduces two new atomic interval types:
1) Interval Year to Month
Supports a range of [-10,000..10,000] years, with month-level precision. Typically stored as separate integers for years and months (e.g., 12y 3m), but only the total number of months is considered significant. For example, 1y 0m is equivalent to 0y 12m or 1001y -12000m.
2) Interval Day to Second
Supports a range of [-3,650,000..3,650,000] days, with second precision. Typically stored as separate integers for days and seconds, but only the total number of seconds is considered significant. For example, 1d 0s is equivalent to 0d 86400s.
=> feat: introduce `interval_year` and `interval_day` types

lib/Dialect/Substrait/IR/Substrait.cpp
This comment makes clear why we do not test if the `seconds` value as part of the `IntervalDaySecondAttr` type is within the required interval range [-315,360,000,000..315,360,000,000]. This is because the `seconds` value is an int32_t, and this interval range exceeds the limits of int32_t.
=> chore: add comment to `IntervalDaySecondAttr` verify function

include/substrait-mlir/Dialect/Substrait/IR/SubstraitAttrs.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/literal.mlir, test/Dialect/Substrait/types.mlir, test/Target/SubstraitPB/Export/literal.mlir, test/Target/SubstraitPB/Export/types.mlir, test/Target/SubstraitPB/Import/literal.textpb, test/Target/SubstraitPB/Import/types.textpb
This PR introduces the UUID type: a universally-unique identifier composed of 128 bits.
=> feat: introduce `uuid` types

CMakeLists.txt
This PR does some minor clean-ups of the main CMakes file:
* Remove a call to `include_directories` with a variable that wasn't set.
* Rename a variable from `_DIRS` to `_DIR` because it only holds a single directory.
=> build: minor clean-ups of the main `CMakeLists.txt`

.github/workflows/build_and_test.yml, CMakeLists.txt, README.md, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, lib/Target/SubstraitPB/ProtobufUtils.cpp, test/python/dialects/substrait/translate.py
This PR upgrades the codebase to the more recent Protobuf version downloaded and compiled by `substrait-cpp`. Previously, we used `find_package` from our CMake files, even though we don't use those targets directly and only use those imported by `substrait-cpp` already. Also, since recently, `substrait-cpp` can download Protobuf if none is installed in the systems, so we rely on that mechanism in CI now. Since that version is newer than the one we used in CI until now, the PR also updates the code base to the new version.
The PR suppresses some warnings in the headers of the new Protobuf version, which are errors in CI due to our using of `-Werror`, by setting some diagnostic pragmas. However, it would be better if those headers were imported as `SYSTEM` headers by `substrait-cpp`, but I …
=> build: use and adapt to more recent Protobuf from `substrait-cpp`

include/substrait-mlir/Dialect/Substrait/IR/CMakeLists.txt, lib/Dialect/Substrait/IR/CMakeLists.txt
For a while, CI sporadically fails due to some generated headers not being found. I have finally understood why this happens. This PR fixes the dependencies among the generated headers and the main dialect target.
=> build: fix CMake dependencies for generated headers

python/CMakeLists.txt
This appears to only be an issue on MSVC.
=> feat: add missing LLVMSupport link

CMakeLists.txt
Resolves https://github.com/substrait-io/substrait-mlir-contrib/issues/103.
=> build: remove unnecessary (incorrect) LLVM CMake includes

.github/workflows/build_and_test.yml, include/substrait-mlir/Target/SubstraitPB/Export.h, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/python/dialects/substrait/e2e_datafusion.py, test/python/dialects/substrait/e2e_duckdb.py, test/python/dialects/substrait/e2e_pyarrow.py, third_party/CMakeLists.txt, utils/find_vs.ps1
Collection of a few nits to make MSVC happy + CI support for Windows.
Python binding tests have been XFAIL'ed for now due to .dll initialization issues for Windows. This is most likely due to some erroneous configuration re. python path or perhaps incompatible pybound(nanobound) modules are being picked up. Since I won't be needing those bindings anytime soon, i suggest getting the PR in as is (getting Windows building + CI) and creating an issue to track the python issue.
=> feat: windows nits and CI

include/substrait-mlir/Dialect/Substrait/IR/SubstraitAttrs.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/literal-invalid.mlir, test/Dialect/Substrait/literal.mlir, test/Dialect/Substrait/types-invalid.mlir, test/Dialect/Substrait/types.mlir, test/Target/SubstraitPB/Export/literal.mlir, test/Target/SubstraitPB/Import/literal.textpb, test/Target/SubstraitPB/Import/types.textpb
Adds the required type and attribute to support decimal values. A decimal value is modelled as an `IntegerAttr` of `i128` and a `DecimalType`. Decimal types follow the constraints outlined in the [substrait docs](https://substrait.io/types/type_classes/).
This is a follow up of #98 and resolves #96.
=> feat: add support for decimal values

include/substrait-mlir/Dialect/Substrait/IR/SubstraitEnums.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/aggregate.mlir, test/Target/SubstraitPB/Export/aggregate.mlir, test/Target/SubstraitPB/Import/aggregate.textpb
~~This PR is based on and, therefor, includes #70.~~
This PR adds the `aggregation_phase` to the `call` op, which corresponds to the `phase` field of the `AggregationFunction` message. The PR also revisits the assembly format of the `aggregation_invocation` attribute of the `call` op and now handles the two jointly such that either of the two can be ommitted if it has the default value. Finally, the PR revisits the LIT tests such that both aggregation detauls are tested jointly and explicitly instead of being piggy-backed onto the remaining tests. This is the last non-type feature we need to run TPC-H Q6 as produced by Isthmus.
=> feat: implement `aggregation_phase` of `call` op

requirements-unfrozen.txt, requirements.txt, test/Target/SubstraitPB/Round-Trip/simple.json, test/lit.cfg.py, test/lit.site.cfg.py.in, tools/scripts/normalize_json.py
This PR adds some infrastructure for testing that Substrait plans round-trip through `substrait-mlir` without loosing any information. This is currently based on the JSON format and consist in comparing (1) a normalized version of the input plan with (2) a normalized version of the plan after round-tripping it through `substrait-mlir`. JSON is maybe the format that makes this easiest and most robust since normalizing JSON can be done with mature tools (deserialize from and reserialize to JSON). The PR also extends LIT to run these tests and adds a test case that exercises the round-trip testing infrastructure on a couple of plans based on the `plan.mlir` cases from the current dialect tests.
=> test: add tooling for new `Round-Trip` test type

include/substrait-mlir/Dialect/Substrait/IR/SubstraitAttrs.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/literal.mlir, test/Dialect/Substrait/types.mlir, test/Target/SubstraitPB/Export/literal.mlir, test/Target/SubstraitPB/Export/types.mlir, test/Target/SubstraitPB/Import/literal.textpb, test/Target/SubstraitPB/Import/types.textpb
This PR introduces the varchar<L> compound type, which represents a variable-length Unicode string of up to L characters.
=> feat: introduce `varchar<L>` type

include/substrait-mlir/Dialect/Substrait/IR/SubstraitAttrs.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitTypes.td, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/literal.mlir, test/Dialect/Substrait/types.mlir, test/Target/SubstraitPB/Export/literal.mlir, test/Target/SubstraitPB/Export/types.mlir, test/Target/SubstraitPB/Import/literal.textpb, test/Target/SubstraitPB/Import/types.textpb
This PR is based on and, therefor, contains #82.
This PR introduces the compound type `fixedBinary<L>` representing a binary string of L bytes.
=> feat: introduce `fixedbinary<L>` type

include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, test/Dialect/Substrait/extension-table.mlir, test/Dialect/Substrait/plan.mlir, test/Dialect/Substrait/project.mlir, test/Target/SubstraitPB/Export/extension-table.mlir, test/Target/SubstraitPB/Export/plan.mlir, test/Target/SubstraitPB/Export/project.mlir, test/Target/SubstraitPB/Import/extension-table.textpb, test/Target/SubstraitPB/Import/plan.textpb, test/Target/SubstraitPB/Import/project.textpb
Substrait represents several types of extensions as `google.protobuf.any` messages, which consist of a value, which a byte sequence of a binary Protobuf message, and a URL. Turns out that `some protobuf message` is not a valid binary Protobuf message and `some url` is not a valid Protobuf schema URL. This wans't a problem for round-tripping between our dialect and Protobufs in either text or binary format but the JSON format requires both to be valid (and known, in the case of the URL).
This PR, thus, changes the URL and value fields of all `any` messages and the corresponding type and detail fields of the extension attributes in the test cases in order to allow for round-tripping them through JSON.
=> test: use valid URLs and values for extension test cases

test/Target/SubstraitPB/Export/named-table.mlir, test/Target/SubstraitPB/Import/named-table.textpb
These seem to have been forgotten in the past. Most feature were tested as part of the tests of `PlanOp`, though.
=> test: add explicit import/export tests for `NamedTableOp`

include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Dialect/Substrait/Transforms/EmitDeduplication.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, test/Dialect/Substrait/aggregate.mlir, test/Dialect/Substrait/cross.mlir, test/Dialect/Substrait/extension-table.mlir, test/Dialect/Substrait/fetch.mlir, test/Dialect/Substrait/filter.mlir, test/Dialect/Substrait/join.mlir, test/Dialect/Substrait/named-table.mlir, test/Dialect/Substrait/set.mlir, test/Target/SubstraitPB/Export/aggregate.mlir, test/Target/SubstraitPB/Export/cross.mlir, test/Target/SubstraitPB/Export/extension-table.mlir, test/Target/SubstraitPB/Export/fetch.mlir, test/Target/SubstraitPB/Export/filter.mlir, test/Target/SubstraitPB/Export/join.mlir, test/Target/SubstraitPB/Export/named-table.mlir, test/Target/SubstraitPB/Export/set.mlir, test/Target/SubstraitPB/Import/aggregate.textpb, test/Target/SubstraitPB/Import/cross.textpb, test/Target/SubstraitPB/Import/extension-table.textpb, test/Target/SubstraitPB/Import/fetch.textpb, test/Target/SubstraitPB/Import/filter.textpb, test/Target/SubstraitPB/Import/join.textpb, test/Target/SubstraitPB/Import/named-table.textpb, test/Target/SubstraitPB/Import/set.textpb
This PR adds the `advanced_extension` to the remaining ops corresponding to `*Rel` message types by adding the corresponding attribute, extending the assembly format, and adding custom builders to be able to skip the new attribute.
=> feat: add `advanced_extension` attribute to remaining `*Rel`s

lib/Dialect/Substrait/IR/Substrait.cpp
... in case the defining op is a block argument, which in turn would previously result in a crash.
=> feat: dyn_cast_or_null EmitOp's input defining op

.github/workflows/coverage_stats.yml, .github/workflows/markdown.yml, .markdownlint.jsonc, README.md, docs/stats.md, docs/stats/Makefile, docs/stats/stats.py, requirements-unfrozen.txt, requirements.txt
This PR adds a script that computes statistics on how much of the Substrait specification is currently covered by this project based on which of the protobuf fields of the spec occur in the "import" test cases. The PR also adds a new CI target that checks whether the markdown file holding the spec is up-to-date and fails with an error message indicating how to update that file in case that's necessary.
=> feat: implement script that produces stats on spec coverage

include/substrait-mlir/Dialect/Substrait/IR/SubstraitInterfaces.td, include/substrait-mlir/Dialect/Substrait/IR/SubstraitOps.td
Partly motivated by not having a long list of legal ops, mostly motivated by increasing the interoperability of the dialect, allowing other dialects to mark ops with `PlanBodyOpInterface`, making them legal to nest within a `Substrait_PlanOp`.
=> feat: make plan body ops an interface

requirements-unfrozen.txt, requirements.txt
This includes wjakob/nanobind#939 and wjakob/nanobind#940, which fixes an issue I encountered while working on #78, so we need the new version of `nanobind` for CI to pass and stub generation to be correct for that.
=> chore(deps): update to latest version of `nanobind`

.github/workflows/coverage_stats.yml
This PR fixes the GH workflow that ensures that the coverage stats are up-to-date. The workflow is supposed to print a message in case the stats need to be updated including the command that the developer should run to update them. Due to wrong quoting, that command was actually executed rather than being printed, so this PR changes to quotes to protect the command.
=> fix: print make command instead of executing it in failure message

.github/workflows/build_and_test.yml, .github/workflows/clang_format.yml, .github/workflows/coverage_stats.yml, .github/workflows/licence_check.yml, .github/workflows/markdown.yml, .github/workflows/pr_title.yml, .github/workflows/yapf.yml
This PR makes all CI jobs use `ubuntu-24.04` as the runner image. Previously, either `ubuntu-22.04` or `ubuntu-latest` was used; the former is a bit outdated and the latter is prone to breaking CI jobs due to an image update.
=> ci: use `ubuntu-24.04` for all CI jobs on Linux

lib/CAPI/CMakeLists.txt, lib/Dialect/Substrait/IR/CMakeLists.txt, lib/Target/SubstraitPB/CMakeLists.txt, tools/substrait-lsp-server/CMakeLists.txt, tools/substrait-opt/CMakeLists.txt, tools/substrait-translate/CMakeLists.txt
While preparing the BUILD files for bazel, I ran into missing direct dependencies. Bazel can notice if a build target uses a particular dependency but only declares that dependency *indirectyl*, i.e., there is a dependency a -> b -> c, even though a uses c directly. This often works but may break if the dependencies of the intermediate target change, so it is better to always declare all dependencies directly.
=> build: add direct CMake dependencies and order alphabetically

tools/scripts/normalize_json.py
A `Generator[x, None, None]` is expressed simpler as `Iterator[x]`, which this PR applies to the `normalize_json.py` utility.
=> style: simplify type annotation for `Iterator`

.clang-tidy, .github/workflows/build_and_test.yml, CMakeLists.txt, README.md, python/CMakeLists.txt
This PR sets up clang-tidy to be run by CMake on our targets. Currently
all checks that fail are disabled such that CI continues to pass.
=> build: set up clang-tidy

.clang-tidy, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp
That flag was disabled when `clang-tidy` was set up initially in #140 because it failed in too many places. This PR enables it and applies the automatic fixes such that identifier naming will be enforced in the future.
=> build: enable `readability-identifier-naming` check of `clang-tidy`

test/lit.cfg.py, test/python/dialects/substrait/translate.py
This PR moves the disabling of Python's output buffering to a `-u` flag in the `RUN` line of each individual lit test. Without this configuration, the output on stdout from Python gets delayed with respect to the output from native libraries (such as the MLIR Python bindings) such that the order is not preserved and `FileCheck` checks fail. Previously, the configuration was don in `lit.cfg.py` but that file may not be used by other test runners.
=> test: unbuffer Python with CLI flag rather than lit config

python/substrait_mlir/dialects/substrait.py, test/python/dialects/substrait/translate.py
This PR cleans up two import statements that made Google-internal usages more complicated than necessary. The clean-ups also represent real improvements, independent of that use case, though: in `substrait.py` an import statement importing a single module used the multi-line syntax (with parentheses) and in `translate.py`, an import statement imported two submodules (which is less readable than separate import statement per module).
=> style: clean up import statements in Python files

.clang-tidy, .github/workflows/clang_format.yml, BUILD.bazel, WORKSPACE.bazel, include/substrait-mlir/Dialect/Substrait/IR/Substrait.h, lib/CAPI/Dialects.cpp, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Dialect/Substrait/Transforms/EmitDeduplication.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, lib/Target/SubstraitPB/ProtobufUtils.cpp, tools/substrait-lsp-server/substrait-lsp-server.cpp, tools/substrait-opt/substrait-opt.cpp, tools/substrait-translate/substrait-translate.cpp
This PR depends on and, therefore, includes ~~#144 and~~ #142.
This may seem in contrast with the LLVM Coding Standards, which mandates to "include as little as possible." However, it does say that "[we] **must** include all of the header files that [we] are using," though it gives the freedom to do that "either directly or indirectly through another header file." The rule is, in fact, mainly targeted at forward declarations of classes that aren't "used" in the C++ sense with the goal of reducing compile time. Using the `misc-include-cleaner`, thus, seems like a good compromise: it allows to enforce removing unused headers, which improves compile time, at the expense of not being able to indirectly include other headers anymore, which is arguably a minor disadvantage.
This PR also adds a …
=> style: enable `clang-tidy`'s `misc-include-cleaner` check

.clang-tidy, lib/Dialect/Substrait/IR/Substrait.cpp, lib/Target/SubstraitPB/ProtobufUtils.cpp, tools/substrait-lsp-server/substrait-lsp-server.cpp, tools/substrait-opt/substrait-opt.cpp, tools/substrait-translate/substrait-translate.cpp
That flag was disabled when `clang-tidy` was set up initially in #140 because it failed in too many places. This PR enables it and fixes all instances found by `clang-tidy` such that the style will be enforced in the future.
=> build: enable `misc-use-anonymous-namespace` check of `clang-tidy`

lib/Dialect/Substrait/IR/Substrait.cpp, test/Dialect/Substrait/literal.mlir, test/Dialect/Substrait/project.mlir, test/Dialect/Substrait/types.mlir, test/Target/SubstraitPB/Export/literal.mlir, test/Target/SubstraitPB/Export/types.mlir, test/Target/SubstraitPB/Import/literal.textpb, test/Target/SubstraitPB/Import/types.textpb
This PR adds a short-hand version for the assymbly format of the types in the Substrait dialect and adapts the tests accordingly.  The implementation follows the same pattern as the one in the [LLVMIR dialect](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/LLVMIR/IR/LLVMTypeSyntax.cpp) upstream. With that format, we can write `interval_ds` instead of `!substrait.interval_day_second`, for example. The short-hand versions mainly consist of just the op name e.g., `date` instead of `!substrait.date` but a few short-hand versions are shortend further (like `interval_ds`). The short-hand versions can be used everywhere were the custom `SubstraitType` printer and parser is used. For now, this includes all `RelOp`s, the `YieldOp`, as well as types tested inside `RelationType`, …
=> feat: implement short-hand form for types

.github/workflows/build_and_test.yml
This PR adds another CI target that compiles the project without assertions and that is only enabled as a post-merge check. This addresses substrait-io#158, which tracks the fact that some warnings are only raised when a project is compiled without assertions, most notably when variables are only used by assertions and then become unused. This is a rare and minor issue, so the delay that would be caused by checking for every commit of every PR would not be worth it. The post-merge check is achieved by turning the main CI job for compiling into a `matrix` whose value sets the flag that enables assertions in CMake and then excluding the `ON` entry for all but `push` events (which are triggered after a PR is "pushed" onto main during merge).
=> ci: set up build without assertions as post-merge CI job

.github/dependabot.yml
This PR tries again another format for repositories in the `ignore` field of the configuration of dependabot. What isn't clearly documented is whether this is a *name*  (as specified in `.gitmodule`), a path, or a pattern/regex. The initial configuration only put the folder name (without `third_party` prefix) but that did not work for ignoring the `llvm-project` dependency (which was specified for the `/` directory. #151 then tried to prepend `third_party/` everywhere, but this seems to
have broken the `allow` field of the `llvm-project` dependency, which is given in the `third_party/` folder. My best now is that the `ignore` and `allow` fields are interpreted relative to the `directory`, which would explain both previously observed breakages. If that interpretation is correct, we should …
=> ci(dependabot): try yet another format for `ignore`/`allow`

include/substrait-mlir-c/Dialects.h, include/substrait-mlir/Dialect/Substrait/IR/SubstraitEnums.td, include/substrait-mlir/Target/SubstraitPB/Options.h, lib/CAPI/Dialects.cpp, lib/Target/SubstraitPB/Export.cpp, lib/Target/SubstraitPB/Import.cpp, python/CMakeLists.txt, python/SubstraitDialects.cpp, python/stubgen.patterns, python/substrait_mlir/dialects/substrait.py, test/python/dialects/substrait/translate.py, tools/substrait-translate/substrait-translate.cpp
This PR refactors the handling of the various serialization formats of the Substrait protobuf messages, in particular, on a Python level. Previously, the various `to_*` and `from_*` functions where implemented in C++ using `nanobind`, which is arguable cumbersome. The new implementation only implements a single import and export function, repsepectively, which gets an enum argument for the format. For that purpose, the PR also exposes that enum via `nanobind`. The previously existing import and export functions are now implemented in Python, where they are essentially one-liners calling the new functions.
=> refactor: move format handling from nanobind to Python
